apiVersion: kontinue.io/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: tap-supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web

  components:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: git-repository-battery

    - name: built-image-provider
      templateRef:
        kind: ClusterImageTemplate
        name: kpack-battery
      sources:
        - component: source-provider
          name: solo-source-provider

    - name: knative-service-provider
      templateRef:
        kind: ClusterConfigTemplate
        name: knative-service-battery
      images:
        - component: built-image-provider
          name: solo-image-provider
