
---
apiVersion: kontinue.io/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: git-repository-battery
spec:
  urlPath: .status.artifact.url
  revisionPath: .status.artifact.revision

  template:
    apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    metadata:
      name: $(workload.metadata.name)$-source
    spec:
      interval: 3m
      url: $(workload.spec.source.git.url)$
      ref: $(workload.spec.source.git.ref)$
      gitImplementation: libgit2
      ignore: ""


---
apiVersion: kontinue.io/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: kpack-battery
spec:
  imagePath: .status.latestImage

  template:
    apiVersion: kpack.io/v1alpha1
    kind: Image
    metadata:
      name: $(workload.metadata.name)$-image
    spec:
      tag: harbor.amer.end2end.link/kontinuedemo/$(workload.metadata.name)$
      serviceAccount: service-account
      builder:
        kind: ClusterBuilder
        name: default
      source:
        blob:
          url: $(sources[0].url)$

---
apiVersion: kontinue.io/v1alpha1
kind: ClusterConfigTemplate
metadata:
  name: knative-service-battery
spec:
  configPath: .status.template
  template: 
    apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      name: $(workload.metadata.name)$-service
    spec:
     template:
      spec:
       containers:
        - image: $(images[0].image)$
          env:
            - name: TARGET
              value: "this is a test environment variable"
